a1authenticationsys/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ticketsystem.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

ticketsystem/urls.py
from django.urls import path
from django.views.generic import RedirectView
from ticketsystem.views import IncorrectTicketIdView, IndexView
from . import views

app_name = 'ticketsystem'

urlpatterns = [
    path('', RedirectView.as_view(url='success/'), name='index'),
    path('success/', IndexView.as_view(), name='Success'),
    path('incorrect-ticket-id/', IncorrectTicketIdView.as_view(), name='incorrect'),
    path('generate/', views.create_ticket, name='create_ticket'),
    path('admins/', views.adminView, name='Administrator'),
    # path('admins/', AdminView.as_view(), name='Administrator')
]

ticketsystem/models.py
from django.db import models
from django.contrib.auth.models import User


class TicketModel(models.Model):
    status_list = (
        ('Active', 'Active'),
        ('Used', 'Used')
    )
    ticket_id = models.OneToOneField(
        User, on_delete=models.CASCADE)
    duration = models.CharField(max_length=4)
    status = models.CharField(choices=status_list, max_length=7)

ticketsystem/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import TicketModel

from ticketsystem.random_string_gen import usernameGenerator, passwordGenerator


# username and password filesave function
def fileSave(username, password):
    f = open('usernamePassword.txt', 'a+')
    f.write('%s, %s \n' % (username, password))
    f.close()


class IndexView(LoginRequiredMixin, View):
    template_name = 'ticket_sys/success-login.html'
    login_url = '/accounts/login'
    redirect_field_name = '/'

    def get(self, request):
        return render(request, self.template_name)


class IncorrectTicketIdView(View):
    template_name = 'ticket_sys/incorrect-ticket-id.html'

    def get(self, request):
        return render(request, self.template_name)


# class AdminView(View):
#     template_name = 'ticket_sys/admin.html'
#     model = TicketModel

#     def get(self, request):
#         return render(request, self.template_name)

@login_required
def adminView(request):
    ticket = User.objects.all()
    context = {
        'ticket': ticket
    }
    return render(request, 'ticket_sys/admin.html', context)


@login_required
def create_ticket(request):
    username = usernameGenerator()
    password = passwordGenerator()
    fileSave(username, password)
    ticket = User.objects.create_user(username=username, password=password)
    ticket.save()

    newUsername = User.objects.get(username=username).username

    output = '''
    <html>
      <head>
        <title>
          Generate Ticket ID
        </title>
      </head>
      <body>
        Generated Ticket ID: %s
      </body>
    </html>''' % (
        newUsername
    )

    return HttpResponse(output)

ticketsystem/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>A1 Technologies Ticket System</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>

<body>
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}

    <footer>
        <div class="container footer-center">
            <h6>&copy; A1 Technologies. </h6>
        </div>
    </footer>

    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
</body>

</html>

ticketsystem/templates/navbar.html
{% load static %}
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'ticketsystem:index' %}">
                <img alt="Brand" src="{% static 'img/a1-logo.png' %}" id="logo-img">
            </a>
        </div>
    </div>
</nav>

ticketsystem/templates/ticket_sys/admin.html
{% extends 'base.html' %}
{% block content %}


<div class="container">
    <div class="text-center">
        <form action="{% url 'ticketsystem:create_ticket' %}" method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Generate">
        </form>
    </div>

    <table class=" table table-bordered">

        <thead>
            <tr>
                <th>S/N</th>
                <th>Ticket ID</th>
                <th>Duration</th>
                <th>Status</th>
            </tr>
        </thead>
        {% for t in ticket %}
        <tbody>
            <td>{{ t.id }}</td>
            <td>{{ t.username }}</td>
            <td>1 Hr</td>
            <td class="green">Active</td>
        </tbody>
        {% endfor %}
    </table>
</div>



{% endblock %}

ticketsystem/templates/ticket_sys/empty-field.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>A1 Technologies Ticket System</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="css/main.css">
</head>

<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">
                    <img alt="Brand" src="img/a1-logo.png" id="logo-img">
                </a>
            </div>
        </div>
    </nav>

    <div class="ticket-id">
        <div class="container">
            <div class="text-center">
                <h3>Ticket ID</h3>
                <small>Input your 10 Digit Key</small>
            </div>
            <div class="row">
                <div class="col-md-4">

                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <form action="" class="form-control"></form>
                        <small class="red">Field is Empty</small>
                    </div>
                    <button class="btn btn-primary center">Login</button>
                </div>
                <div class="col-md-4">

                </div>
            </div>
        </div>
    </div>

    <footer>
        <div class="container footer-center">
            <h4>&copy; A1 Technologies. </h4>
        </div>
    </footer>

    <script src="js/jquery-3.2.1.min.js"></script>
    <script src="js/bootstrap.js"></script>
</body>

</html>

ticketsystem/templates/ticket_sys/incorrect-ticket-id.html
{% extends 'base.html' %}
{%  block content %}
<div class="ticket-id">
    <div class="container">
        <div class="text-center">
            <h3>Ticket ID</h3>
            <small>Input your 10 Digit Key</small>
        </div>
        <div class="row">
            <div class="col-md-4">

            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <form action="" class="form-control"></form>
                </div>
                <div class="red text-center">
                    <h5>Incorrect Ticked ID</h5>
                    <h6>Try Again</h6>
                </div>
                <button class="btn btn-primary center">Login</button>
            </div>
            <div class="col-md-4">

            </div>
        </div>
    </div>
</div>
{% endblock %}

ticketsystem/templates/ticket_sys/index.html
{% extends 'base.html' %}
{% block content %}

<div class="ticket-id">
    <div class="container">
        <div class="text-center">
            <h3>Ticket ID</h3>
            <small>Input your 10 Digit Key</small>
        </div>
        <div class="row">
            <div class="col-md-4">

            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <form action="/login_view" method="POST">
                        <p>
                            <label for="id_username">Username:</label>
                            <input type="text" class="form-control" name='username' maxlength='100' required>
                        </p>

                        <p>
                            <label for="id_password">Password:</label>
                            <input type="password" class="form-control">
                        </p>

                    </form>

                </div>
                <div class="text-center">
                    <input type="submit" value="Login" class="btn btn-primary">

                </div>
            </div>
            <div class="col-md-4">

            </div>
        </div>
    </div>
</div>

{% endblock %}

ticketsystem/templates/ticket_sys/success-login.html
{% extends 'base.html' %}
{% block content %}
<div class="ticket-id">
    <div class="container">
        <div class="text-center">
            <h4>Successfully Logged In With</h4>
            {% if user.is_authenticated %}
            <h1 class="green"><strong>{{ user.username }}</strong></h1>
            {% endif %}
            <div class="time-remaining">
                <h3>Time Remaining</h3>
                <strong>0:09:17</strong>
            </div>
        </div>
    </div>
</div>
{% endblock %}